#!/usr/bin/env python3
"""Bake tools/webportal.html into src/webpage_data.h as a gzip blob.

The page carries its own font and artwork so it renders with no internet at all — the
phone is on the launcher's own hotspot. Those two files live in tools/assets/ and are
substituted for the @FONT@ / @CAT@ tokens here, which keeps the HTML itself readable.

Browsers accept gzip natively, so the result is stored compressed and served with
Content-Encoding: gzip — smaller in flash and faster over the hotspot.

  --preview <path>   also write the resolved HTML somewhere, to open in a browser.
"""
import base64
import gzip
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, "webportal.html")
OUT = os.path.join(os.path.dirname(HERE), "src", "webpage_data.h")

# token -> file baked in as a data: URI payload
ASSETS = {
    "@FONT@": "assets/silkscreen-ascii.woff2",  # Silkscreen, SIL OFL 1.1 (assets/OFL.txt)
    "@CAT@": "assets/cat-stealth.gif",          # Oreo Cat by Aichan_owo
}

html = open(SRC, "r", encoding="utf-8").read()
for token, rel in ASSETS.items():
    if token not in html:
        continue
    blob = open(os.path.join(HERE, rel), "rb").read()
    html = html.replace(token, base64.b64encode(blob).decode("ascii"))
    print(f"{token:8s} {rel:34s} {len(blob):>7,} bytes")

if "--preview" in sys.argv:
    path = sys.argv[sys.argv.index("--preview") + 1]
    open(path, "w", encoding="utf-8").write(html)
    print("preview ->", path)

raw = html.encode("utf-8")
gz = gzip.compress(raw, 9)

with open(OUT, "w") as f:
    f.write("#pragma once\n#include <stdint.h>\n")
    f.write("// Generated by tools/make_webpage.py from tools/webportal.html - do not edit.\n")
    f.write(f"// {len(raw)} bytes of HTML -> {len(gz)} bytes gzipped.\n")
    f.write(f"static const uint8_t kWebPageGz[{len(gz)}] = {{\n   ")
    for i, b in enumerate(gz):
        f.write(" 0x%02X," % b)
        if i % 20 == 19:
            f.write("\n   ")
    f.write("\n};\n")

print(f"{len(raw):,} bytes HTML -> {len(gz):,} bytes gzip ({100 - len(gz)*100//len(raw)}% smaller)")
print("wrote ->", OUT)
