#!/usr/bin/env python3
"""Regenerate src/icons_data.h from 48x48 icon PNGs (rendered from MDI SVGs).

The icons are Material Design Icons (Pictogrammers, Apache-2.0), fetched from the
Iconify API, rasterized white-on-transparent, and packed here as 1-bit masks so the
launcher can tint them in any accent-contrast colour on the carousel pills.

Pipeline (host, one-off):
  curl the SVGs  ->  node render.js (resvg)  ->  PNGs  ->  this script  ->  icons_data.h
Point PNG_DIR at the folder of <NAME>.png files and run with the PlatformIO python.
"""
import os

# Order MUST match enum Icon in display.h (index 0 = IC_NONE, a blank entry).
# New icons must be APPENDED, never inserted: theme packs (icons.bin) store icons by index,
# so reordering would scramble every pack already in the wild.
ORDER = [
    "NONE", "APP", "EMPTY", "INSTALL", "USB", "SETTINGS", "DESIGN", "DELETE",
    "BACK", "PIN", "ABOUT", "OFF", "LEDBRIGHT", "LEDCOLOR", "ANIM", "COLOR",
    "THEME", "FLASH", "FILE", "CHECK", "WIFI",
    # Pickable per-app-slot icons (see APP_ICONS in apps.cpp).
    "GHOST", "ANTENNA", "BUG", "SKULL", "GAMEPAD", "CHIP", "KEY", "SHIELD",
    "TERMINAL", "NFC", "WRENCH", "STAR",
]
W = H = 48
STRIDE = (W + 7) // 8
ALPHA_TH = 110

HERE = os.path.dirname(os.path.abspath(__file__))
PROJECT = os.path.dirname(HERE)
PNG_DIR = os.environ.get("ICON_PNG_DIR", os.path.join(HERE, "_icons_png"))
OUT = os.path.join(PROJECT, "src", "icons_data.h")


def pack(name):
    from PIL import Image
    b = bytearray(STRIDE * H)
    p = os.path.join(PNG_DIR, name + ".png")
    if name == "NONE" or not os.path.exists(p):
        return b
    im = Image.open(p).convert("RGBA").resize((W, H))
    a = im.split()[3].load()
    for y in range(H):
        for x in range(W):
            if a[x, y] > ALPHA_TH:
                b[y * STRIDE + (x >> 3)] |= (0x80 >> (x & 7))
    return b


def main():
    rows = [pack(n) for n in ORDER]
    with open(OUT, "w") as f:
        f.write("#pragma once\n#include <stdint.h>\n")
        f.write("// Auto-generated by tools/make_icons.py — Material Design Icons (Apache-2.0).\n")
        f.write("// 1-bit masks, MSB-first, row-major. Tinted at draw time (theme-safe).\n")
        f.write(f"#define ICON_W {W}\n#define ICON_H {H}\n#define ICON_STRIDE {STRIDE}\n")
        f.write(f"#define ICON_COUNT {len(ORDER)}\n\n")
        f.write(f"static const uint8_t ICON_BITS[{len(ORDER)}][{STRIDE * H}] = {{\n")
        for n, b in zip(ORDER, rows):
            hexb = ",".join(str(v) for v in b)
            f.write(f"  {{{hexb}}}, // {n}\n")
        f.write("};\n")
    print("wrote", OUT, "count", len(ORDER))


if __name__ == "__main__":
    main()
