#!/usr/bin/env python3
"""Bakes a folder of frames into the built-in boot animation (src/bootanim_data.h).

    python make_embedded_anim.py <frames-folder> [--frames N] [--width 240] [--height 128]

Each frame is centre-cropped to the screen aspect (fills fullscreen, no bars), resized to WxH
and mapped onto ONE shared palette of <=256 RGB565 colours; the resulting one-byte-per-pixel
indices are Deflate-compressed per frame. Storing indices rather than RGB565 halves the input
to the compressor and keeps identical colours byte-identical, so it packs far better.

The device inflates one frame at a time (W*H bytes) and expands it through the palette while
scaling to the full screen. `--frames N` thins evenly to N frames (first and last kept).
"""
import os
import re
import sys
import zlib

from PIL import Image

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(HERE, "src", "bootanim_data.h")


def numeric_key(name):
    m = re.match(r'.*?(\d+)', name)
    return (int(m.group(1)) if m else 0, name)


def subsample(names, keep):
    if not keep or keep >= len(names):
        return names
    step = (len(names) - 1) / (keep - 1)
    return [names[round(i * step)] for i in range(keep)]


def cover_pixels(path, W, H, colors=0):
    """Centre-cropped, resized frame as a flat list of RGB565 values."""
    img = Image.open(path).convert('RGB')
    sw, sh = img.size
    tar, sr = W / H, sw / sh
    if sr > tar:  # too wide -> crop sides
        nw = int(sh * tar)
        x = (sw - nw) // 2
        img = img.crop((x, 0, x + nw, sh))
    else:         # too tall -> crop top/bottom
        nh = int(sw / tar)
        y = (sh - nh) // 2
        img = img.crop((0, y, sw, y + nh))
    img = img.resize((W, H), Image.LANCZOS)
    if colors:  # posterise so the noisy texture collapses onto a small palette
        img = img.quantize(colors=colors, method=Image.FASTOCTREE, dither=Image.Dither.NONE).convert('RGB')
    return [((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3) for r, g, b in img.getdata()]


def build_palette(frames_px, limit=256):
    """One palette for the whole animation, keeping the most common colours and snapping the
    rest to their nearest neighbour (the tail is a fraction of a percent of pixels)."""
    from collections import Counter
    freq = Counter()
    for px in frames_px:
        freq.update(px)
    if len(freq) <= limit:
        pal = sorted(freq)
        return pal, {c: i for i, c in enumerate(pal)}
    pal = [c for c, _ in freq.most_common(limit)]
    trip = [(((c >> 11) & 31) << 3, ((c >> 5) & 63) << 2, (c & 31) << 3) for c in pal]
    lut = {}
    for c in freq:
        r, g, b = ((c >> 11) & 31) << 3, ((c >> 5) & 63) << 2, (c & 31) << 3
        best, bd = 0, 1 << 30
        for i, (tr, tg, tb) in enumerate(trip):
            d = (r - tr) ** 2 + (g - tg) ** 2 + (b - tb) ** 2
            if d < bd:
                bd, best = d, i
        lut[c] = best
    return pal, lut


def main():
    if len(sys.argv) < 2:
        sys.exit(__doc__)
    source = sys.argv[1]

    def arg(flag, default):
        return int(sys.argv[sys.argv.index(flag) + 1]) if flag in sys.argv else default

    W, H = arg('--width', 160), arg('--height', 85)
    frames = arg('--frames', 30)
    colors = arg('--colors', 64)  # 0 = full colour

    names = sorted([n for n in os.listdir(source)
                    if n.lower().endswith(('.jpg', '.jpeg', '.png', '.bmp'))], key=numeric_key)
    if not names:
        sys.exit("No images in %s" % source)
    names = subsample(names, frames)

    frames_px = [cover_pixels(os.path.join(source, n), W, H, colors) for n in names]
    pal, lut = build_palette(frames_px)
    blobs = [zlib.compress(bytes(lut[p] for p in px), 9) for px in frames_px]

    offsets = [0]
    for b in blobs:
        offsets.append(offsets[-1] + len(b))
    payload = b''.join(blobs)
    raw = W * H            # one index byte per pixel now
    total = len(payload) + len(pal) * 2

    print("%d frames, %dx%d, %d-colour palette + Deflate" % (len(names), W, H, len(pal)))
    print("data: %.1f KB  (palette %d B, biggest frame %.1f KB, inflated frame %d B)"
          % (total / 1024, len(pal) * 2, max(len(b) for b in blobs) / 1024, raw))

    with open(OUT, 'w', encoding='utf-8') as h:
        h.write("// Generated by make_embedded_anim.py - do not edit by hand.\n")
        h.write("// Source: %s\n// %d frames, %dx%d, %d-colour palette + Deflate, %d bytes\n"
                % (source, len(names), W, H, len(pal), total))
        h.write("#pragma once\n#include <stdint.h>\n\n")
        h.write("static constexpr uint16_t kBootAnimWidth = %d;\n" % W)
        h.write("static constexpr uint16_t kBootAnimHeight = %d;\n" % H)
        h.write("static constexpr uint16_t kBootAnimFrames = %d;\n" % len(names))
        h.write("// Inflated size of one frame: W*H palette indices.\n")
        h.write("static constexpr uint32_t kBootAnimRawFrameSize = %d;\n\n" % raw)
        h.write("static const uint16_t kBootAnimPalette[%d] = {\n   " % len(pal))
        for i, c in enumerate(pal):
            h.write(" %d," % c)
            if i % 16 == 15:
                h.write("\n   ")
        h.write("\n};\n\n")
        h.write("static const uint32_t kBootAnimOffsets[%d] = {\n   " % len(offsets))
        for i, o in enumerate(offsets):
            h.write(" %d," % o)
            if i % 12 == 11:
                h.write("\n   ")
        h.write("\n};\n\n")
        h.write("static const uint8_t kBootAnimData[%d] = {\n   " % len(payload))
        for i, b in enumerate(payload):
            h.write(" 0x%02X," % b)
            if i % 20 == 19:
                h.write("\n   ")
        h.write("\n};\n")
    print("wrote ->", OUT)


if __name__ == '__main__':
    main()
