#!/usr/bin/env python3
"""Generate src/cat_data.h — Oreo Cat (by Aichan_owo) pixel animations for the launcher.

The cats are pixel art with barely a hundred distinct colours, so each animation is stored as a
palette (RGB565) plus one byte per pixel. Index 0 means transparent, which also removes the need
for a separate alpha mask.

Those indices are then Deflate-compressed: flat pixel art squeezes about 32x, turning ~113 KB of
frames into ~3.5 KB of flash. The launcher shares a 1.5 MB partition with the Wi-Fi stack, so
that headroom matters. The firmware inflates each animation once into PSRAM on first use, with
the same ROM tinfl decoder the boot animation already uses.
"""
import os
import zlib

GIF = r"C:\Users\zilen\Downloads\Oreo Cat - Aichan_owo\Oreo Cat - Aichan_owo\GIF Animations"
HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(os.path.dirname(HERE), "src", "cat_data.h")

# (C name, gif file, frame delay ms, max on-screen height)
ANIMS = [
    ("CAT_SLEEP", "05 Sleep Idle.gif", 200, 88),    # USB drive screen
    ("CAT_ATTACK", "16 Loop Attack.gif", 90, 104),  # installing screen
]
ALPHA_TH = 128


def load_frames(path):
    from PIL import Image
    im = Image.open(path)
    out = []
    for i in range(getattr(im, "n_frames", 1)):
        im.seek(i)
        out.append(im.convert("RGBA"))
    return out


def shared_bbox(frames):
    box = None
    for f in frames:
        b = f.getbbox()
        if b is None:
            continue
        box = b if box is None else (min(box[0], b[0]), min(box[1], b[1]),
                                     max(box[2], b[2]), max(box[3], b[3]))
    return box


def rgb565(r, g, b):
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)


def build(name, gif, delay, maxh, f):
    from PIL import Image
    frames = load_frames(os.path.join(GIF, gif))
    l, t, r, b = shared_bbox(frames)
    w, h = r - l, b - t
    scale = min(1.0, maxh / h)
    w, h = max(1, round(w * scale)), max(1, round(h * scale))

    palette = [0]          # slot 0 is reserved for "transparent"
    lookup = {}
    idx = bytearray()
    for fr in frames:
        crop = fr.crop((l, t, r, b)).resize((w, h), Image.NEAREST)
        px = crop.load()
        for y in range(h):
            for x in range(w):
                pr, pg, pb, pa = px[x, y]
                if pa < ALPHA_TH:
                    idx.append(0)
                    continue
                c = rgb565(pr, pg, pb)
                i = lookup.get(c)
                if i is None:
                    if len(palette) >= 256:
                        i = min(range(1, len(palette)),
                                key=lambda k: abs(palette[k] - c))  # full: reuse nearest
                    else:
                        i = len(palette)
                        palette.append(c)
                        lookup[c] = i
                idx.append(i)

    comp = zlib.compress(bytes(idx), 9)  # zlib stream: tinfl parses it with flag 1
    f.write(f"static const uint16_t {name}_pal[] = {{{','.join(str(v) for v in palette)}}};\n")
    f.write(f"static const uint8_t {name}_z[] = {{{','.join(str(v) for v in comp)}}};\n")
    f.write(f"static const CatAnim {name} = {{{w},{h},{len(frames)},{delay},"
            f"{name}_pal,{name}_z,{len(comp)},{len(idx)}}};\n\n")
    return w, h, len(frames), len(palette), len(comp) + len(palette) * 2


def main():
    with open(OUT, "w") as fo:
        fo.write("#pragma once\n#include <stdint.h>\n")
        fo.write("// Auto-generated by tools/make_cat.py - 'Oreo Cat' by Aichan_owo.\n")
        fo.write("// Palette + 1 byte per pixel, Deflate-compressed; palette index 0 = transparent.\n")
        fo.write("// `z`/`zlen` is the compressed stream, `rawlen` the inflated size (w*h*frames).\n")
        fo.write("typedef struct { uint16_t w, h, frames, delayMs; const uint16_t* pal;"
                 " const uint8_t* z; uint32_t zlen, rawlen; } CatAnim;\n\n")
        info = [(n, build(n, g, d, m, fo)) for n, g, d, m in ANIMS]
    total = 0
    for name, (w, h, n, pal, size) in info:
        print(f"{name}: {w}x{h} x{n} frames, {pal} colours, {size:,} bytes")
        total += size
    print(f"total: {total:,} bytes")


if __name__ == "__main__":
    main()
