#!/usr/bin/env python3
"""Generate src/cyberfont_data.h — proportional 1-bit bitmap atlases from Cyberjunkies.ttf.

Two atlases are emitted:
  CY_L  large, ASCII 32..95 (space..Z, digits, punctuation) — page titles.
  CY_S  small, ASCII 32..126 (full)                          — labels, status, file names.

Each glyph: advance, tight w/h, x/y offset from the pen/line-top, and an offset into a
flat packed-bit blob (MSB-first, stride = ceil(w/8)). The on-device renderer (cyberfont.cpp)
walks glyphs along the baseline and can integer-scale (1x/2x) for crisp big text.
"""
import os
from PIL import Image, ImageDraw, ImageFont

TTF = r"C:\Users\zilen\Downloads\cyberjunkies\Cyberjunkies.ttf"
HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(os.path.dirname(HERE), "src", "cyberfont_data.h")
PREVIEW = os.path.join(HERE, "_font_preview.png")

ATLASES = [
    ("CY_L", 22, 32, 95),
    ("CY_S", 13, 32, 126),
]


def build(size, first, last):
    font = ImageFont.truetype(TTF, size)
    asc, desc = font.getmetrics()
    lineH = asc + desc
    glyphs = []          # (ch, adv, xoff, yoff, w, h, bytes)
    blob = bytearray()
    for cp in range(first, last + 1):
        ch = chr(cp)
        adv = round(font.getlength(ch))
        img = Image.new("L", (size * 2 + 4, lineH + 4), 0)
        d = ImageDraw.Draw(img)
        d.text((2, 2), ch, font=font, fill=255)
        bbox = img.getbbox()
        if bbox is None:  # blank glyph (space)
            glyphs.append((ch, adv, 0, 0, 0, 0, len(blob)))
            continue
        l, t, r, b = bbox
        w, h = r - l, b - t
        stride = (w + 7) // 8
        off = len(blob)
        px = img.load()
        for y in range(t, b):
            row = bytearray(stride)
            for x in range(l, r):
                if px[x, y] >= 128:
                    row[(x - l) >> 3] |= (0x80 >> ((x - l) & 7))
            blob += row
        glyphs.append((ch, adv, l - 2, t - 2, w, h, off))
    return dict(size=size, first=first, last=last, asc=asc, lineH=lineH,
               glyphs=glyphs, blob=blob)


def emit(f, name, a):
    f.write(f"// ---- {name}  size {a['size']}  ascii {a['first']}..{a['last']} ----\n")
    f.write(f"static const uint8_t {name}_bits[] = {{")
    f.write(",".join(str(b) for b in a["blob"]))
    f.write("};\n")
    f.write(f"static const CyGlyph {name}_glyphs[] = {{\n")
    for ch, adv, xo, yo, w, h, off in a["glyphs"]:
        safe = repr(ch) if ch != "\\" else "'backslash'"
        f.write(f"  {{{adv},{w},{h},{xo},{yo},{off}}}, // {ord(ch)} {safe}\n")
    f.write("};\n")
    f.write(f"static const CyFont {name} = {{{a['first']},{a['last']},"
            f"{a['lineH']},{a['asc']},{name}_glyphs,{name}_bits}};\n\n")


def main():
    atl = [(n, build(s, fi, la)) for n, s, fi, la in ATLASES]
    with open(OUT, "w") as f:
        f.write("#pragma once\n#include <stdint.h>\n")
        f.write("// Auto-generated by tools/make_font.py from Cyberjunkies.ttf.\n\n")
        f.write("typedef struct { uint8_t adv, w, h; int8_t xoff, yoff; uint16_t off; } CyGlyph;\n")
        f.write("typedef struct { uint8_t first, last, lineH, ascent;"
                " const CyGlyph* glyphs; const uint8_t* bits; } CyFont;\n\n")
        for n, a in atl:
            emit(f, n, a)
    # round-trip preview from the packed bits (proves the on-device unpack will be right)
    render_preview(atl)
    total = sum(len(a["blob"]) for _, a in atl)
    print("wrote", OUT, "blob bytes", total)


def render_preview(atl):
    canvas = Image.new("RGB", (620, 220), (14, 17, 34))
    d = ImageDraw.Draw(canvas)

    def draw(a, s, x, y, scale, col):
        g = {ch: rec for ch, *rec in
             [(gg[0], gg[1], gg[2], gg[3], gg[4], gg[5], gg[6]) for gg in a["glyphs"]]}
        pen = x
        for ch in s:
            if ch not in g:
                continue
            adv, xo, yo, w, h, off = g[ch]
            stride = (w + 7) // 8
            for yy in range(h):
                for xx in range(w):
                    if a["blob"][off + yy * stride + (xx >> 3)] & (0x80 >> (xx & 7)):
                        px0 = pen + (xo + xx) * scale
                        py0 = y + (yo + yy) * scale
                        d.rectangle([px0, py0, px0 + scale - 1, py0 + scale - 1], fill=col)
            pen += adv * scale
    L = dict((n, a) for n, a in atl)["CY_L"]
    S = dict((n, a) for n, a in atl)["CY_S"]
    draw(L, "SETTINGS", 8, 8, 2, (255, 255, 255))
    draw(L, "INSTALLING", 8, 70, 1, (47, 227, 138))
    draw(S, "Charge  name.bin  0123", 8, 120, 2, (58, 212, 224))
    draw(S, "copy files, then press back", 8, 160, 1, (200, 200, 210))
    canvas.save(PREVIEW)


if __name__ == "__main__":
    main()
